services:
  clickhouse-server:
    container_name: clickhouse-server
    image: clickhouse/clickhouse-server
    environment:
      - CLICKHOUSE_USER=user
      - CLICKHOUSE_PASSWORD=password
      - CLICKHOUSE_DB=ny_taxi
    volumes:
      - "./ny_taxi_clickhouse_data:/var/lib/clickhouse/:rw"
    ports:
      - "8123:8123"
      - "9000:9000"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 3